apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-project-deploy
  labels:
    app: insurance-project-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: insurance-project-app
  template:
    metadata:
      labels:
        app: insurance-project-app
    spec:
      containers:
      - name: insurance-project-container
        image: image: 119694353779.dkr.ecr.us-east-1.amazonaws.com/insurance:latest

        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: insurance-project-np-service
  labels:
    app: insurance-project-app
spec:
  selector:
    app: insurance-project-app

  type: NodePort
  ports:
  - nodePort: 31032    
    port: 8081
    targetPort: 8081
